{{- if eq (include "mlflow.autoGenCertForIngress" .) "true" }}
{{- $ca := genCA "mlflow-ca" 365 }}
{{- $cert := genSignedCert (first .Values.ingress.hosts) nil (rest .Values.ingress.hosts) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-ca
  labels:
     {{- include "mlflow.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}
