apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: kserve-models-web-app
    kustomize.component: kserve-models-web-app
  name: kserve-models-web-app
  namespace: kserve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kserve-models-web-app
    kustomize.component: kserve-models-web-app
  name: kserve-models-web-app-cluster-role
rules:
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - pods/log
      - events
    verbs:
      - get
      - list
  - apiGroups:
      - serving.kserve.io
    resources:
      - inferenceservices
      - inferenceservices/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
      - services/status
      - routes
      - routes/status
      - configurations
      - configurations/status
      - revisions
      - revisions/status
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kserve-models-web-app
    kustomize.component: kserve-models-web-app
  name: kserve-models-web-app-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kserve-models-web-app-cluster-role
subjects:
  - kind: ServiceAccount
    name: kserve-models-web-app
    namespace: kserve
---
apiVersion: v1
data:
  APP_DISABLE_AUTH: "True"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: kserve-models-web-app
    kustomize.component: kserve-models-web-app
  name: kserve-models-web-app-config-9kkt28dhgb
  namespace: kserve
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kserve-models-web-app
    kustomize.component: kserve-models-web-app
  name: kserve-models-web-app
  namespace: kserve
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app.kubernetes.io/component: kserve-models-web-app
    kustomize.component: kserve-models-web-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: kserve-models-web-app
    kustomize.component: kserve-models-web-app
  name: kserve-models-web-app
  namespace: kserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kserve-models-web-app
      kustomize.component: kserve-models-web-app
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kserve-models-web-app
        kustomize.component: kserve-models-web-app
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: kserve-models-web-app-config
          image: kserve/models-web-app:latest
          imagePullPolicy: Always
          name: kserve-models-web-app
          ports:
            - containerPort: 5000
      serviceAccountName: kserve-models-web-app
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/component: kserve-models-web-app
    kustomize.component: kserve-models-web-app
  name: kserve-models-web-app
  namespace: kserve
spec:
  gateways:
    - $(ingressGateway)
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /models/
      rewrite:
        uri: /
      route:
        - destination:
            host: kserve-models-web-app.kserve.svc.cluster.local
            port:
              number: 80
