{{- if or (.Values.mysql.enabled) (.Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-db-conn
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  DB_CONNECT_URL: {{ include "db.connectURL" . | b64enc | quote }}
{{- end }}
