{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-mysql-conn
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  DB_CONNECT_URL: {{ include "mysql.connectURL" . | b64enc | quote }}
{{- end }}
