{{- if .Values.persistence.enabled }}
{{- if not .Values.mysql.enabled }}
{{- $database := .Values.persistence.persistentVolumeClaim.sqlite -}}
{{- if not $database.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mlflow.fullname" . }}-database
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  accessModes: 
    - {{ $database.accessMode }}
  resources:
    requests:
      storage: {{ $database.size }}
  {{- if $database.storageClass }}
    {{- if eq "-" $database.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $database.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}

---
{{- if not .Values.minio.enabled }}
{{- $artifact := .Values.persistence.persistentVolumeClaim.artifact -}}
{{- if not $artifact.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mlflow.fullname" . }}-artifact
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  accessModes: 
    - {{ $artifact.accessMode }}
  resources:
    requests:
      storage: {{ $artifact.size }}
  {{- if $artifact.storageClass }}
    {{- if eq "-" $artifact.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $artifact.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}

---
{{- $metrics := .Values.persistence.persistentVolumeClaim.metrics -}}
{{- if not $metrics.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mlflow.fullname" . }}-metrics
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  accessModes: 
    - {{ $metrics.accessMode }}
  resources:
    requests:
      storage: {{ $metrics.size }}
  {{- if $metrics.storageClass }}
    {{- if eq "-" $metrics.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $metrics.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
