#@data/values-schema
---
namespace: "default"
name_suffix: "fuseml"
#@schema/type any=True
labels: null
aws_access_key_id: ""
aws_region: ""
aws_secret_access_key: ""
s3_compat_api_endpoint: ""
config_configmap_name: ""
gcp_creds_secret_name: ""
grpc_port: 8080
rest_port: 8081
ovms_image_tag: "2021.4.1"
log_level: INFO
model_name: "default"
model_path: ""
models_host_path: ""
models_volume_claim: ""
nireq: ""
plugin_config: '{\"CPU_THROUGHPUT_STREAMS\":\"1\"}'
batch_size: ""
shape: ""
model_version_policy: '{\"latest\": { \"num_versions\":1 }}'
file_system_poll_wait_seconds: 1
replicas: 1
#@schema/type any=True
resources: null
istio_host: ""
istio_gateway: "ovms-gateway"
